# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
